[features]
seeds = false
skip-lint = false
[programs.localnet]
token_contract = "DmWrigyYrGHWu8NsCadhJVXY6BxaJsaDHDD7E3ywgL9W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xapski2671/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
